use master
CREATE DATABASE ClubConquistadores
go
USE ClubConquistadores
go

CREATE TABLE CONQUISTADORES(
id int PRIMARY KEY,
fechaNacimiento date NOT NULL,
edad int NOT NULL,
nombrePila nvarchar (50) NOT NULL,
apellidoPaterno nvarchar(50) NOT NULL,
apellidoMaterno nvarchar(50) NOT NULL,
sexo nchar(1) NOT NULL)

CREATE TABLE ALERGIAS(
id int PRIMARY KEY,
nombre nvarchar(50) NOT NULL,
descripcion nvarchar(200))

CREATE TABLE ALERGIASCONQUISTADORES(
idAlergia int REFERENCES ALERGIAS(id) NOT NULL,
idConquistadores int REFERENCES Conquistadores(id) NOT NULL)

CREATE TABLE PADRES(
id int UNIQUE FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
ocupacion nvarchar(50) NOT NULL)

CREATE TABLE TELEFONOSPADRES(
id int FOREIGN KEY REFERENCES PADRES(id) NOT NULL,
telefono nvarchar(10) NOT NULL)

CREATE TABLE PADRESDECONQUISTADORES(
idPadres int FOREIGN KEY REFERENCES PADRES(id) NOT NULL,
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL)

CREATE TABLE ESPECIALIDADES(
id int PRIMARY KEY,
nombre nvarchar(50) UNIQUE NOT NULL)

CREATE TABLE CLUBS(
id int PRIMARY KEY,
nombre nvarchar(50) NOT NULL,
direccion nvarchar(100) NOT NULL,
logo image NOT NULL)

CREATE TABLE CONQUISTADORESCLUBS(
idClub int FOREIGN KEY REFERENCES CLUBS(id) NOT NULL,
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
rol nvarchar(20) NOT NULL,
fechaInicio date NOT NULL,
fechaFinal date,
tiempo date,
vigencia bit NOT NULL)

CREATE TABLE UNIDADES(
id int PRIMARY KEY,
nombre nvarchar(50) NOT NULL,
logotipo image NOT NULL,
sexo nchar(1) NOT NULL,
lema nvarchar(50) NOT NULL)

CREATE TABLE CONQUISTADORESUNIDADES(
idUnidad int FOREIGN KEY REFERENCES UNIDADES(id) NOT NULL,
idConquistadores int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
rol nvarchar(20) NOT NULL)

CREATE TABLE NECESITAN_ACTUALIZACION(
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
idEspecialidades int FOREIGN KEY REFERENCES ESPECIALIDADES(id) NOT NULL)

CREATE TABLE REQUISITOS(
id int PRIMARY KEY,
idEspecialidad int FOREIGN KEY REFERENCES ESPECIALIDADES(id) NOT NULL,
descripcion nvarchar(200) NOT NULL)

CREATE TABLE CONQUISTADORESREQUISITOS(
idRequisito int FOREIGN KEY REFERENCES REQUISITOS(id) NOT NULL,
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
fechaFinalizado date NOT NULL,
UNIQUE (idRequisito,idConquistador))

ALTER TABLE CONQUISTADORESREQUISITOS ALTER COLUMN fechaFinalizado date

CREATE TABLE CONQUISTADORESESPECIALIDAD(
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
idEspecialidad int FOREIGN KEY REFERENCES ESPECIALIDADES(id) NOT NULL,
fechaObtenida date NOT NULL
UNIQUE(idConquistador,idEspecialidad))

CREATE TABLE CLASES(
id int PRIMARY KEY,
nombre nvarchar(50) UNIQUE NOT NULL,
color nvarchar(50) NOT NULL,
logotipo image NOT NULL)

CREATE TABLE IMPARTENSCLASES(
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
idClase int FOREIGN KEY REFERENCES CLASES(id) NOT NULL,
idEspecialidad int FOREIGN KEY REFERENCES ESPECIALIDADES(id) NOT NULL,
fechaInicial date NOT NULL,
fechaFinal date, 
vigencia bit NOT NULL)

CREATE TABLE ASISTENCIASCONQUISTADORES(
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
idClase int FOREIGN KEY REFERENCES CLASES(id) NOT NULL,
vigecia bit NOT NULL)

CREATE TABLE ESTADOASISTENCIAS(
idConquistador int FOREIGN KEY REFERENCES CONQUISTADORES(id) NOT NULL,
fechaEstado date NOT NULL,
asistencia bit NOT NULL)
GO